# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a0ff8907dec8dab3a5b7fa3182903487064148608d52d74ad09302d179cf1c529c402ccb3ea2f3d0d0a884463e67b6c81cf4cae4a417678ddb13acd1b056978

test:
  secret_key_base: 1cbdcda02aaec38013e188078b226ffa26f02b2c23dbe8cd6d6898200421d4392cea4bb8dcd9b062599e3664007b4264b4bdac7c28a2964494017b2533bfe35b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
